version: '3'
services:
  rails:
    build: .
    # To run without the debugger
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "3000:3000"
      - "1234:1234"
      - "26162:26162"
  
volumes:
  gems:
    external: false # flagging this as false means docker compose will control its creation